# M3 Simulator Usage

### Action space
<img width=40% src=./usages/action.png>

In [1]:
from gym_match3.envs import Match3Env
from gym_match3.envs.levels import LEVELS #  default levels
from gym_match3.envs.levels import Match3Levels, Level
from gym_match3.envs.game import *

matcher = MatchesSearcher(3, 2)

# create an instance with extended levels
custom_m3_levels = Match3Levels(levels=LEVELS) 
env = Match3Env(levels=custom_m3_levels)

KeyboardInterrupt: 

In [ ]:
env.render()

[[14. 14.  2.  4.  5.  1.  2.  1.  5.]
 [14. 14.  1.  2.  1.  2.  4.  1.  2.]
 [ 5.  4.  5.  3.  3.  2.  1.  2.  1.]
 [ 3.  5.  3.  1.  5.  4.  2.  1.  2.]
 [ 4.  1.  3.  2.  1.  5.  4.  5.  4.]
 [ 1.  5.  4.  1.  2.  4.  4.  1.  3.]
 [ 3.  4.  3.  1.  3.  1.  3.  3.  4.]
 [ 2.  5.  1.  3.  3.  2. 14. 14.  3.]
 [ 4.  5.  4.  1.  1.  3. 14. 14.  3.]
 [ 2.  3.  1.  3.  3.  1.  4.  1.  1.]]


In [ ]:
env.step(159)
env.render()

frozenset({(8, 7), (9, 7)})
[]
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
abc False
{'score': 0, 'damage_on_monster': 0, 'damage_on_user': 0}
[[14. 14.  2.  4.  5.  1.  2.  1.  5.]
 [14. 14.  1.  2.  1.  2.  4.  1.  2.]
 [ 5.  4.  5.

In [1]:
from gym_match3.envs.game import *

game = Game(rows=3, columns=3, n_shapes=5,
                         length=3, random_state=1)
board = np.array([
    [9, 1, 1],
    [1, 15, 1],
    [11, 1, 2]
])
                 
blocker = BlockerFactory.create_blocker(11, Point(2, 0))
list_monsters = [
        BoxMonster(15, position=Point(1, 1),
                   relax_interval = 0,
                   setup_interval = 0,
                    width=1,
                    height=1,
                    hp=30
                    ),
        blocker]
game.start(board, list_monsters)
print(game.swap(Point(0, 0), Point(1, 0)))
print(game.list_monsters)
print(game.board)

{'score': 2, 'cancel_score': 0, 'damage_on_monster': 1, 'damage_on_user': 0}
[<gym_match3.envs.game.BoxMonster object at 0x0000020C892B20D0>, <gym_match3.envs.game.BombBlocker object at 0x0000020C892C00D0>, <gym_match3.envs.game.BombBlocker object at 0x0000020C892C0A30>]
[[ 4. 11.  1.]
 [ 5. 15.  1.]
 [11.  1.  2.]]


In [2]:
print(game.swap(Point(2, 1), Point(2, 2)))
print(game.board)

not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hvae move
not hv

KeyboardInterrupt: 